name: Retail ETL CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Run Unit Tests
        run: |
          pytest -v

      - name: Create Build Folder
        run: |
          mkdir build

      - name: Install Lambda Dependencies
        run: |
          pip install -r requirements-lambda.txt -t build

      - name: Copy Source
        run: |
          cp -r src/* build/

      - name: Create Lambda ZIP
        run: |
          cd build
          zip -r ../lambda.zip .

      - name: Verify ZIP
        run: |
          ls -lh
          unzip -l lambda.zip | head -20

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda.zip