name: Retail ETL CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-build-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Test Dependencies
        run: |
          pip install --no-cache-dir -r src/requirements.txt

      - name: Run Unit Tests
        run: |
          pytest -v

      - name: Create Build Directory
        run: |
          mkdir -p build

      - name: Install Lambda Dependencies
        run: |
          pip install --no-cache-dir -r requirements-lambda.txt -t build

      - name: Copy Source Code
        run: |
          cp -r src/* build/

      - name: Build Lambda ZIP
        run: |
          cd build
          zip -r ../lambda.zip .

      - name: Verify Lambda Package
        run: |
          ls -lh
          unzip -l lambda.zip | head -30

      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity

      - name: Verify Lambda Exists
        run: |
          aws lambda get-function \
            --function-name RetailPipelineLambda

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name RetailPipelineLambda \
            --zip-file fileb://lambda.zip

      - name: Wait for Lambda Deployment
        run: |
          aws lambda wait function-updated \
            --function-name RetailPipelineLambda

      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --function-name RetailPipelineLambda \
            --payload '{}' \
            response.json

      - name: Show Lambda Response
        run: |
          cat response.json